FROM richarvey/nginx-php-fpm:1.9.0

RUN apk update && apk add mysql-client subversion

# Install and configure WP CLI.
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar; \
  chmod +x wp-cli.phar; \
  mv wp-cli.phar /usr/local/bin/; \
  # Workaround for root usage scolding.
  echo -e "#!/bin/bash\n\n/usr/local/bin/wp-cli.phar \"\$@\" --allow-root\n" > /usr/local/bin/wp; \
  chmod +x /usr/local/bin/wp;

# Download WordPress.
ARG WP_VERSION=latest
RUN wp core download --version=$WP_VERSION

# Copy the plugin into the right place.
COPY actblue-contributions /var/www/html/wp-content/plugins/actblue-contributions

# Make the e2e script executable.
RUN chmod +x /var/www/html/wp-content/plugins/actblue-contributions/bin/install-wp-e2e-tests.sh