version: 2.1

references:
  # Environment variables.
  WP_CORE_DIR: &WP_CORE_DIR
    /tmp/wordpress
  WP_PLUGIN_NAME: &WP_PLUGIN_NAME
    actblue-contributions
  WP_ORG_USERNAME: &WP_ORG_USERNAME
    actblue
  WP_TESTS_DIR: &WP_TESTS_DIR
    /tmp/wordpress-tests-lib
  WP_HOST: &WP_HOST
    actblue.test

  # Container configuration.
  container_config: &container_config
    docker:
      - image: circleci/php:7.2-node-browsers
    environment:
      - WP_CORE_DIR: *WP_CORE_DIR
      - WP_PLUGIN_NAME: *WP_PLUGIN_NAME
      - WP_ORG_USERNAME: *WP_ORG_USERNAME
      - WP_TESTS_DIR: *WP_TESTS_DIR
    working_directory: ~/actblue-contributions

  workspace_root: &workspace_root
    /tmp

  install_subversion: &install_subversion
    run:
      name: Install subversion
      command: sudo apt-get update && sudo apt-get install subversion

  attach: &attach
    attach_workspace:
      at: *workspace_root

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd $WP_PLUGIN_NAME
            composer install -n -o
            npm install
      - run:
          name: Build
          command: cd $WP_PLUGIN_NAME && npm run build
      - run:
          name: Install WordPress
          command: bash .circleci/install-wp.sh
      - persist_to_workspace:
          root: .
          paths:
            - actblue-contributions/vendor
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - wordpress

  code_quality:
    <<: *container_config
    steps:
      - checkout
      - *attach
      - run:
          name: Copy vendor directory
          command: cp -R /tmp/$WP_PLUGIN_NAME/vendor $WP_PLUGIN_NAME
      - run:
          name: Run code quality tests
          command: cd $WP_PLUGIN_NAME && vendor/bin/phpcs

  unit_tests:
    <<: *container_config
    docker:
      - image: circleci/php:7.2
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - *install_subversion
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install default-mysql-client
            sudo docker-php-ext-install mysqli
            composer global require "phpunit/phpunit ^5"
      - run:
          name: Run unit tests
          command: |
            rm -rf $WP_TESTS_DIR $WP_CORE_DIR
            bash $WP_PLUGIN_NAME/bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
            cd $WP_PLUGIN_NAME && $HOME/.composer/vendor/bin/phpunit

  e2e_tests:
    <<: *container_config
    docker:
      - image: circleci/php:7.2-node
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - run:
          name: Add WordPress host to hosts file
          command: echo "127.0.0.1 ${WP_HOST}" | sudo tee -a /etc/hosts
      - run:
          name: Install Headless Chrome dependencies
          command: |
            sudo apt-get update && sudo apt-get install -yq \
            gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
            libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
            libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 \
            libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates \
            fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libgbm-dev
      - run:
          name: Install puppeteer with chronium
          command: npm install puppeteer
      - *attach
      - run:
          name: Copy vendor directory
          command: cp -R /tmp/vendor .
      - run:
          name: Install MySQL client
          command: sudo apt-get install mysql-client
      - run:
          name: Install MySQL PHP extension
          command: sudo docker-php-ext-install mysqli
      - run:
          name: Install dependencies
          command: cd $WP_PLUGIN_NAME && npm install
      - run:
          name: Build
          command: cd $WP_PLUGIN_NAME && npm run build
      - run:
          name: Setup WordPress
          command: .circleci/setup-wordpress.sh
      - run:
          name: Start PHP server
          command: sudo php -S $WP_HOST:80 -t $WP_CORE_DIR
          background: True
      - run:
          name: Run e2e tests
          command: cd $WP_PLUGIN_NAME && npm run test:e2e -- --wordpress-base-url=http://${WP_HOST}


  deploy_assets:
    <<: *container_config
    steps:
      - checkout
      - *attach
      - *install_subversion
      - run:
          name: Deploy assets to WordPress plugin directory
          command: .circleci/deploy-assets.sh

  deploy_plugin:
    <<: *container_config
    steps:
      - checkout
      - *attach
      - *install_subversion
      - run:
          name: Deploy assets to WordPress plugin directory
          command: .circleci/deploy-plugin.sh

workflows:
  version: 2
  run_tests:
    jobs:
      # - build
      - e2e_tests
      # - code_quality:
      #     requires:
      #       - build
      # - unit_tests:
      #     requires:
      #       - build
      # - deploy_assets:
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
      # - deploy_plugin:
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
