version: 2

references:
  # Environment variables.
  WP_CORE_DIR: &WP_CORE_DIR
    /tmp/wordpress
  WP_HOST: &WP_HOST
    actblue.test
  WP_ORG_PLUGIN_NAME: &WP_ORG_PLUGIN_NAME
    actblue
  WP_ORG_USERNAME: &WP_ORG_USERNAME
    actblue
  WP_TESTS_DIR: &WP_TESTS_DIR
    /tmp/wordpress-tests-lib

  # Container configuration.
  container_config: &container_config
    docker:
      - image: circleci/php:7.2
    environment:
      - WP_CORE_DIR: *WP_CORE_DIR
      - WP_HOST: *WP_HOST
      - WP_ORG_PLUGIN_NAME: *WP_ORG_PLUGIN_NAME
      - WP_ORG_USERNAME: *WP_ORG_USERNAME
      - WP_TESTS_DIR: *WP_TESTS_DIR
    working_directory: ~/actblue

  workspace_root: &workspace_root
    /tmp

  attach: &attach
    attach_workspace:
      at: *workspace_root

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd actblue && composer install -n -o
      - run:
          name: Install WordPress
          command: bash .circleci/install-wp.sh
      - persist_to_workspace:
          root: .
          paths:
            - actblue/vendor
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - wordpress

  code_quality:
    <<: *container_config
    steps:
      - checkout
      - *attach
      - run:
          name: Copy vendor directory
          command: cp -R /tmp/actblue/vendor actblue
      - run:
          name: Run code quality tests
          command: cd actblue && vendor/bin/phpcs

  unit_tests:
    <<: *container_config
    docker:
      - image: circleci/php:7.2
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - run:
          name: Install subversion
          command: sudo apt-get update && sudo apt-get install subversion
      - run:
          name: Install mysql client
          command: sudo apt-get update && sudo apt-get install default-mysql-client
      - run:
          name: Add mysql docker package
          command: sudo docker-php-ext-install mysqli
            # sudo sh -c "printf '\ndeb http://ftp.us.debian.org/debian sid main\n' >> /etc/apt/sources.list"
      - run:
          name: Install PHPUnit
          command: composer global require "phpunit/phpunit=5.7.*"
      - run:
          name: Run unit tests
          command: |
            rm -rf $WP_TESTS_DIR $WP_CORE_DIR
            bash actblue/bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
            $HOME/.composer/vendor/bin/phpunit

workflows:
  version: 2
  run_tests:
    jobs:
      - build
      # - code_quality:
      #     requires:
      #       - build
      - unit_tests:
          requires:
            - build